name: Release

on:
  workflow_run:
    workflows: [Laravel WebAuthn workflow]
    types: [completed]

  workflow_dispatch:


jobs:
  ####################
  # Semantic release
  ####################
  semantic-release:
    needs: tests
    runs-on: ubuntu-latest
    name: Semantic release
    if: github.event_name != 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Get all tags

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN_RELEASE: ${{ secrets.GH_TOKEN_RELEASE }}
        with:
          semantic_version: 17.3.7
          extra_plugins: |
            @semantic-release/changelog
            semantic-release-github-pullrequest

      - name: New release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: echo ${{ steps.semantic.outputs.new_release_version }}

      - name: Store changelog file
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: CHANGELOG.md
